appname: app

server:
  appmode: dev
  http_port: 9999

mysql:
  host: 127.0.0.1:3306
  user: root
  password: 123456
  dbname: test
  charset: utf8mb4

redis:
  host: 127.0.0.1:6379
  password:
  db: 0
  max_active: 30


mongodb:
  host: 127.0.0.1
  port: 27017
  user: root
  password: 123456
  dbname: test
  poolsize: 10


alioss:
  oss_key: qqq
  oss_secret: qqq
  oss_role_acs: qqq
  oss_bucket:  qqq
es:
  url : http://127.0.0.1:32776
  user :
  password :



